version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build: .
    command: python main_consumer.py
    deploy:
      replicas: 1
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy

  dlq_consumer:
    build: .
    command: python dlq_consumer.py
    restart: always
    working_dir: /app
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
